//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由工具生成。
//
// 对此文件的更改可能会导致不正确的行为，并且如果
// 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyjb.Compilers;

using ComponentModel = global::System.ComponentModel;
using ResourceManager = global::System.Resources.ResourceManager;
using CultureInfo = global::System.Globalization.CultureInfo;

/// <summary>
/// 一个强类型的资源类，用于查找本地化的字符串等。
/// </summary>
/// <remarks>此类是由 T4 文本模板通过 Visual Studio 的工具自动生成的。
/// 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 T4 模板。
/// </remarks>
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
internal partial class Resources
{
	#nullable enable

	private static ResourceManager? resourceManager;
	private static CultureInfo? resourceCulture;

	/// <summary>
	/// 获取此类使用的缓存的 <see cref="ResourceManager"/> 实例。
	/// </summary>
	[ComponentModel.EditorBrowsable(ComponentModel.EditorBrowsableState.Advanced)]
	internal static ResourceManager ResourceManager
	{
		get
		{
			if (resourceManager is null)
			{
				resourceManager = new ResourceManager("Cyjb.Compilers.Resources", typeof(Resources).Assembly);
			}
			return resourceManager;
		}
	}

	/// <summary>
	/// 获取或设置资源使用的区域信息。
	/// </summary>
	[ComponentModel.EditorBrowsable(ComponentModel.EditorBrowsableState.Advanced)]
	internal static CultureInfo? Culture
	{
		get
		{
			return resourceCulture;
		}
		set
		{
			resourceCulture = value;
		}
	}
	
	/// <summary>
	/// 返回类似 <c>Cannot include class \{0} in character range.</c> 的本地化字符串。
	/// </summary>
	internal static string BadClassInCharRange(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("BadClassInCharRange", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>Symbol identifier '{0}' is already exists.</c> 的本地化字符串。
	/// </summary>
	internal static string DuplicatedSymbolId(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("DuplicatedSymbolId", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>Duplicate lexer context '{0}'.</c> 的本地化字符串。
	/// </summary>
	internal static string DuplicateLexerContext(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("DuplicateLexerContext", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>Empty regex</c> 的本地化字符串。
	/// </summary>
	internal static string EmptyRegex => ResourceManager.GetString("EmptyRegex", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Illegal \ at end of pattern.</c> 的本地化字符串。
	/// </summary>
	internal static string IllegalEndEscape => ResourceManager.GetString("IllegalEndEscape", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Incomplete lexer context.</c> 的本地化字符串。
	/// </summary>
	internal static string IncompleteLexerContext => ResourceManager.GetString("IncompleteLexerContext", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Incomplete regex reference.</c> 的本地化字符串。
	/// </summary>
	internal static string IncompleteRegexReference => ResourceManager.GetString("IncompleteRegexReference", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Invalid lexer context '{0}'.</c> 的本地化字符串。
	/// </summary>
	internal static string InvalidLexerContext(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("InvalidLexerContext", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>Invalid lexer symbol '{0}': {1}.</c> 的本地化字符串。
	/// </summary>
	internal static string InvalidLexerSymbol(object? arg0, object? arg1)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("InvalidLexerSymbol", resourceCulture)!, Format(arg0), Format(arg1));
	}
	
	/// <summary>
	/// 返回类似 <c>Invalid lexer symbol action '{0}', parameter must empty or optional.</c> 的本地化字符串。
	/// </summary>
	internal static string InvalidLexerSymbolAction(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("InvalidLexerSymbolAction", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>Invalid regex options</c> 的本地化字符串。
	/// </summary>
	internal static string InvalidRegexOptions => ResourceManager.GetString("InvalidRegexOptions", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Invalid regular expression pattern '{0}' at offset {1}: {2}.</c> 的本地化字符串。
	/// </summary>
	internal static string InvalidRegexPattern(object? arg0, object? arg1, object? arg2)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("InvalidRegexPattern", resourceCulture)!, Format(arg0), Format(arg1), Format(arg2));
	}
	
	/// <summary>
	/// 返回类似 <c>Invalid symbol identifier '{0}'.</c> 的本地化字符串。
	/// </summary>
	internal static string InvalidSymbolId(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("InvalidSymbolId", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>Invalid symbol kind</c> 的本地化字符串。
	/// </summary>
	internal static string InvalidSymbolKind => ResourceManager.GetString("InvalidSymbolKind", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Incomplete \p{X} character escape.</c> 的本地化字符串。
	/// </summary>
	internal static string InvalidUnicodePropertyEscape => ResourceManager.GetString("InvalidUnicodePropertyEscape", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Malformed \p{X} character escape.</c> 的本地化字符串。
	/// </summary>
	internal static string MalformedUnicodePropertyEscape => ResourceManager.GetString("MalformedUnicodePropertyEscape", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Missing control character.</c> 的本地化字符串。
	/// </summary>
	internal static string MissingControl => ResourceManager.GetString("MissingControl", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Nested anchor on beginning of line.</c> 的本地化字符串。
	/// </summary>
	internal static string NestedBeginningOfLine => ResourceManager.GetString("NestedBeginningOfLine", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Nested anchor on end of line.</c> 的本地化字符串。
	/// </summary>
	internal static string NestedEndOfLine => ResourceManager.GetString("NestedEndOfLine", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Nested quantifier {0}.</c> 的本地化字符串。
	/// </summary>
	internal static string NestedQuantify(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("NestedQuantify", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>Nested trailing regex.</c> 的本地化字符串。
	/// </summary>
	internal static string NestedTrailing => ResourceManager.GetString("NestedTrailing", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Not enough )'s.</c> 的本地化字符串。
	/// </summary>
	internal static string NotEnoughParens => ResourceManager.GetString("NotEnoughParens", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>'{0}' not extends LexerController&lt;T&gt;.</c> 的本地化字符串。
	/// </summary>
	internal static string NotExtendsLexerController(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("NotExtendsLexerController", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>Quantifier must be less than or equal to Int32.MaxValue.</c> 的本地化字符串。
	/// </summary>
	internal static string QuantifierOutOfRange => ResourceManager.GetString("QuantifierOutOfRange", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Quantifier {x,y} following nothing.</c> 的本地化字符串。
	/// </summary>
	internal static string QuantifyAfterNothing => ResourceManager.GetString("QuantifyAfterNothing", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>[x-y] range in reverse order.</c> 的本地化字符串。
	/// </summary>
	internal static string ReversedCharRange => ResourceManager.GetString("ReversedCharRange", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Illegal {x,y} with x &gt; y.</c> 的本地化字符串。
	/// </summary>
	internal static string ReversedQuantifierRange => ResourceManager.GetString("ReversedQuantifierRange", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>A subtraction must be the last element in a character class.</c> 的本地化字符串。
	/// </summary>
	internal static string SubtractionMustBeLast => ResourceManager.GetString("SubtractionMustBeLast", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Insufficient hexadecimal digits.</c> 的本地化字符串。
	/// </summary>
	internal static string TooFewHex => ResourceManager.GetString("TooFewHex", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Too many )'s.</c> 的本地化字符串。
	/// </summary>
	internal static string TooManyParens => ResourceManager.GetString("TooManyParens", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Undefined regex '{0}'.</c> 的本地化字符串。
	/// </summary>
	internal static string UndefinedRegex(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("UndefinedRegex", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>Unrecognized control character.</c> 的本地化字符串。
	/// </summary>
	internal static string UnrecognizedControl => ResourceManager.GetString("UnrecognizedControl", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Unrecognized escape sequence \{0}.</c> 的本地化字符串。
	/// </summary>
	internal static string UnrecognizedEscape(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("UnrecognizedEscape", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>Unrecognized grouping construct.</c> 的本地化字符串。
	/// </summary>
	internal static string UnrecognizedGrouping => ResourceManager.GetString("UnrecognizedGrouping", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Unknown Unicode property '{0}'.</c> 的本地化字符串。
	/// </summary>
	internal static string UnrecognizedUnicodeProperty(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("UnrecognizedUnicodeProperty", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>Unterminated [] set.</c> 的本地化字符串。
	/// </summary>
	internal static string UnterminatedBracket => ResourceManager.GetString("UnterminatedBracket", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Unterminated (?#...) comment.</c> 的本地化字符串。
	/// </summary>
	internal static string UnterminatedComment => ResourceManager.GetString("UnterminatedComment", resourceCulture)!;
	
	/// <summary>
	/// 将指定对象格式化为字符串。
	/// </summary>
	/// <param name="value">要格式化的对象。</param>
	private static object Format(object? value)
	{
		if (value == null)
		{
			return "(null)";
		}
		return value;
	}

	#nullable restore

}

