//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyjb.Compilers {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyjb.Compilers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot include class \{0} in character range. 的本地化字符串。
        /// </summary>
        internal static string BadClassInCharRange {
            get {
                return ResourceManager.GetString("BadClassInCharRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Symbol identifier &apos;{0}&apos; is already exists. 的本地化字符串。
        /// </summary>
        internal static string DuplicatedSymbolId {
            get {
                return ResourceManager.GetString("DuplicatedSymbolId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty character classes. 的本地化字符串。
        /// </summary>
        internal static string EmptyCharClass {
            get {
                return ResourceManager.GetString("EmptyCharClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Illegal \ at end of pattern. 的本地化字符串。
        /// </summary>
        internal static string IllegalEndEscape {
            get {
                return ResourceManager.GetString("IllegalEndEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incomplete lexer context. 的本地化字符串。
        /// </summary>
        internal static string IncompleteLexerContext {
            get {
                return ResourceManager.GetString("IncompleteLexerContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incomplete regex reference. 的本地化字符串。
        /// </summary>
        internal static string IncompleteRegexReference {
            get {
                return ResourceManager.GetString("IncompleteRegexReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid regular expression pattern &apos;{0}&apos; at offset {1}: {2} 的本地化字符串。
        /// </summary>
        internal static string InvalidRegexPattern {
            get {
                return ResourceManager.GetString("InvalidRegexPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid symbol identifier &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string InvalidSymbolId {
            get {
                return ResourceManager.GetString("InvalidSymbolId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incomplete \p{X} character escape. 的本地化字符串。
        /// </summary>
        internal static string InvalidUnicodePropertyEscape {
            get {
                return ResourceManager.GetString("InvalidUnicodePropertyEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Malformed \p{X} character escape. 的本地化字符串。
        /// </summary>
        internal static string MalformedUnicodePropertyEscape {
            get {
                return ResourceManager.GetString("MalformedUnicodePropertyEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing control character. 的本地化字符串。
        /// </summary>
        internal static string MissingControl {
            get {
                return ResourceManager.GetString("MissingControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nested anchor on beginning of line. 的本地化字符串。
        /// </summary>
        internal static string NestedBeginningOfLine {
            get {
                return ResourceManager.GetString("NestedBeginningOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nested end of file. 的本地化字符串。
        /// </summary>
        internal static string NestedEndOfFile {
            get {
                return ResourceManager.GetString("NestedEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nested anchor on end of line. 的本地化字符串。
        /// </summary>
        internal static string NestedEndOfLine {
            get {
                return ResourceManager.GetString("NestedEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nested quantifier {0}. 的本地化字符串。
        /// </summary>
        internal static string NestedQuantify {
            get {
                return ResourceManager.GetString("NestedQuantify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nested trailing regex. 的本地化字符串。
        /// </summary>
        internal static string NestedTrailing {
            get {
                return ResourceManager.GetString("NestedTrailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not enough )&apos;s. 的本地化字符串。
        /// </summary>
        internal static string NotEnoughParens {
            get {
                return ResourceManager.GetString("NotEnoughParens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reject action is not supported by current TokenReader&lt;T&gt;. 的本地化字符串。
        /// </summary>
        internal static string NotRejectable {
            get {
                return ResourceManager.GetString("NotRejectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 parsing &quot;{0}&quot; - {1} 的本地化字符串。
        /// </summary>
        internal static string ParsingException {
            get {
                return ResourceManager.GetString("ParsingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quantifier must be less than or equal to Int32.MaxValue. 的本地化字符串。
        /// </summary>
        internal static string QuantifierOutOfRange {
            get {
                return ResourceManager.GetString("QuantifierOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quantifier {x,y} following nothing. 的本地化字符串。
        /// </summary>
        internal static string QuantifyAfterNothing {
            get {
                return ResourceManager.GetString("QuantifyAfterNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [x-y] range in reverse order. 的本地化字符串。
        /// </summary>
        internal static string ReversedCharRange {
            get {
                return ResourceManager.GetString("ReversedCharRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Illegal {x,y} with x &gt; y. 的本地化字符串。
        /// </summary>
        internal static string ReversedQuantifierRange {
            get {
                return ResourceManager.GetString("ReversedQuantifierRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A subtraction must be the last element in a character class. 的本地化字符串。
        /// </summary>
        internal static string SubtractionMustBeLast {
            get {
                return ResourceManager.GetString("SubtractionMustBeLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insufficient hexadecimal digits. 的本地化字符串。
        /// </summary>
        internal static string TooFewHex {
            get {
                return ResourceManager.GetString("TooFewHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too many )&apos;s. 的本地化字符串。
        /// </summary>
        internal static string TooManyParens {
            get {
                return ResourceManager.GetString("TooManyParens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undefined regex &apos;{0]&apos;. 的本地化字符串。
        /// </summary>
        internal static string UndefinedRegex {
            get {
                return ResourceManager.GetString("UndefinedRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized control character. 的本地化字符串。
        /// </summary>
        internal static string UnrecognizedControl {
            get {
                return ResourceManager.GetString("UnrecognizedControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized escape sequence \{0}. 的本地化字符串。
        /// </summary>
        internal static string UnrecognizedEscape {
            get {
                return ResourceManager.GetString("UnrecognizedEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized grouping construct. 的本地化字符串。
        /// </summary>
        internal static string UnrecognizedGrouping {
            get {
                return ResourceManager.GetString("UnrecognizedGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown Unicode property &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string UnrecognizedUnicodeProperty {
            get {
                return ResourceManager.GetString("UnrecognizedUnicodeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unterminated [] set. 的本地化字符串。
        /// </summary>
        internal static string UnterminatedBracket {
            get {
                return ResourceManager.GetString("UnterminatedBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unterminated (?#...) comment. 的本地化字符串。
        /// </summary>
        internal static string UnterminatedComment {
            get {
                return ResourceManager.GetString("UnterminatedComment", resourceCulture);
            }
        }
    }
}
